"""
◈ Parallax Studio - ComfyUI Edition
Apple SHARP Nodes

Your Photos. Alive.
"""

import os
import torch
import numpy as np
from pathlib import Path
from PIL import Image
import subprocess
import tempfile
import folder_paths

# Register custom model folder
folder_paths.add_model_folder_path("sharp", os.path.join(folder_paths.models_dir, "sharp"))


class SHARPModelLoader:
    """Load Apple SHARP model for 3D Gaussian Splatting extraction."""
    
    @classmethod
    def INPUT_TYPES(cls):
        checkpoint_dir = os.path.join(folder_paths.models_dir, "sharp")
        os.makedirs(checkpoint_dir, exist_ok=True)
        
        checkpoints = [f for f in os.listdir(checkpoint_dir) if f.endswith('.pt')] if os.path.exists(checkpoint_dir) else []
        if not checkpoints:
            checkpoints = ["sharp_2572gikvuh.pt (auto-download)"]
        
        return {
            "required": {
                "checkpoint": (checkpoints, {"default": checkpoints[0] if checkpoints else ""}),
            }
        }
    
    RETURN_TYPES = ("SHARP_MODEL",)
    RETURN_NAMES = ("model",)
    FUNCTION = "load_model"
    CATEGORY = "Parallax Studio/SHARP"

    def load_model(self, checkpoint):
        checkpoint_dir = os.path.join(folder_paths.models_dir, "sharp")
        checkpoint_path = os.path.join(checkpoint_dir, checkpoint.replace(" (auto-download)", ""))
        
        # Auto-download if needed
        if not os.path.exists(checkpoint_path):
            print("[Parallax Studio] Downloading SHARP checkpoint from HuggingFace...")
            checkpoint_path = self._download_checkpoint(checkpoint_dir)
        
        print(f"[Parallax Studio] ✓ SHARP model ready: {checkpoint_path}")
        
        # Return path for CLI usage
        return ({"checkpoint_path": checkpoint_path, "mode": "cli"},)
    
    def _download_checkpoint(self, checkpoint_dir):
        from huggingface_hub import hf_hub_download
        os.makedirs(checkpoint_dir, exist_ok=True)
        
        path = hf_hub_download(
            repo_id="apple/Sharp",
            filename="sharp_2572gikvuh.pt",
            local_dir=checkpoint_dir
        )
        return path


class SHARPPredict:
    """Run SHARP prediction to extract 3D Gaussian Splat from image."""
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("SHARP_MODEL",),
                "image": ("IMAGE",),
            }
        }
    
    RETURN_TYPES = ("GAUSSIAN_SPLAT",)
    RETURN_NAMES = ("gaussian_splat",)
    FUNCTION = "predict"
    CATEGORY = "Parallax Studio/SHARP"

    def predict(self, model, image):
        # Convert ComfyUI image tensor to PIL
        if isinstance(image, torch.Tensor):
            image_np = (image[0].cpu().numpy() * 255).astype(np.uint8)
            pil_image = Image.fromarray(image_np)
        else:
            pil_image = image
        
        print("[Parallax Studio] Extracting 3D structure with SHARP...")
        
        with tempfile.TemporaryDirectory() as temp_dir:
            input_dir = Path(temp_dir) / "input"
            output_dir = Path(temp_dir) / "output"
            input_dir.mkdir()
            output_dir.mkdir()
            
            # Save input image
            input_path = input_dir / "frame.png"
            pil_image.save(input_path)
            
            # Run SHARP CLI
            checkpoint_path = model["checkpoint_path"]
            cmd = [
                "sharp", "predict",
                "-i", str(input_dir),
                "-o", str(output_dir),
                "-c", checkpoint_path
            ]
            
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                raise RuntimeError(f"SHARP prediction failed: {result.stderr}")
            
            # Load the generated PLY
            ply_files = list(output_dir.glob("*.ply"))
            if not ply_files:
                raise RuntimeError("No PLY file generated by SHARP")
            
            gaussian_splat = self._load_gaussian_ply(ply_files[0])
        
        print("[Parallax Studio] ✓ 3D Gaussian splat created!")
        
        return (gaussian_splat,)
    
    def _load_gaussian_ply(self, ply_path):
        """Load Gaussian splat from PLY file."""
        from plyfile import PlyData
        
        plydata = PlyData.read(str(ply_path))
        vertex = plydata['vertex']
        
        return {
            "positions": np.stack([vertex['x'], vertex['y'], vertex['z']], axis=-1),
            "scales": np.stack([vertex['scale_0'], vertex['scale_1'], vertex['scale_2']], axis=-1),
            "rotations": np.stack([vertex['rot_0'], vertex['rot_1'], vertex['rot_2'], vertex['rot_3']], axis=-1),
            "sh_coeffs": np.stack([vertex['f_dc_0'], vertex['f_dc_1'], vertex['f_dc_2']], axis=-1),
            "opacities": np.array(vertex['opacity']),
            "ply_path": str(ply_path)
        }


class ParallaxCameraPath:
    """Generate camera path for parallax rendering."""
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "path_type": ([
                    "horizontal_oscillation",
                    "vertical_oscillation", 
                    "circular",
                    "push_pull",
                    "figure_eight"
                ], {"default": "horizontal_oscillation"}),
                "amplitude": ("FLOAT", {"default": 0.15, "min": 0.01, "max": 0.5, "step": 0.01}),
                "total_frames": ("INT", {"default": 300, "min": 30, "max": 1800, "step": 30}),
                "fps": ("INT", {"default": 30, "min": 24, "max": 60, "step": 1}),
                "easing": (["sinusoidal", "linear", "ease_in_out"], {"default": "sinusoidal"}),
            }
        }
    
    RETURN_TYPES = ("CAMERA_PATH",)
    RETURN_NAMES = ("camera_path",)
    FUNCTION = "generate_path"
    CATEGORY = "Parallax Studio/Render"

    def generate_path(self, path_type, amplitude, total_frames, fps, easing):
        t = np.linspace(0, 2 * np.pi, total_frames, endpoint=False)
        
        # Apply easing
        if easing == "sinusoidal":
            phase = t
        elif easing == "linear":
            phase = t
        elif easing == "ease_in_out":
            normalized = t / (2 * np.pi)
            smoothed = normalized * normalized * (3 - 2 * normalized)
            phase = smoothed * 2 * np.pi
        
        # Generate path based on type
        if path_type == "horizontal_oscillation":
            x = amplitude * np.sin(phase)
            y = np.zeros_like(t)
            z = np.zeros_like(t)
        elif path_type == "vertical_oscillation":
            x = np.zeros_like(t)
            y = amplitude * np.sin(phase)
            z = np.zeros_like(t)
        elif path_type == "circular":
            x = amplitude * np.sin(phase)
            y = amplitude * np.cos(phase) * 0.3
            z = np.zeros_like(t)
        elif path_type == "push_pull":
            x = np.zeros_like(t)
            y = np.zeros_like(t)
            z = amplitude * np.sin(phase) * 0.5
        elif path_type == "figure_eight":
            x = amplitude * np.sin(phase)
            y = amplitude * np.sin(phase * 2) * 0.3
            z = np.zeros_like(t)
        
        duration = total_frames / fps
        print(f"[Parallax Studio] Camera path: {path_type}, {duration:.1f}s, {total_frames} frames")
        
        camera_path = {
            "positions": np.stack([x, y, z], axis=-1),
            "total_frames": total_frames,
            "fps": fps,
            "path_type": path_type,
            "amplitude": amplitude
        }
        
        return (camera_path,)


class GaussianSplatRenderer:
    """Render frames from Gaussian Splat using camera path."""
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "gaussian_splat": ("GAUSSIAN_SPLAT",),
                "camera_path": ("CAMERA_PATH",),
                "width": ("INT", {"default": 5120, "min": 640, "max": 8192, "step": 64}),
                "height": ("INT", {"default": 1440, "min": 360, "max": 4320, "step": 64}),
            }
        }
    
    RETURN_TYPES = ("IMAGE",)
    RETURN_NAMES = ("frames",)
    FUNCTION = "render"
    CATEGORY = "Parallax Studio/Render"

    def render(self, gaussian_splat, camera_path, width, height):
        from gsplat import rasterization
        
        device = "cuda"
        
        # Convert to tensors
        means = torch.tensor(gaussian_splat["positions"], dtype=torch.float32, device=device)
        scales = torch.exp(torch.tensor(gaussian_splat["scales"], dtype=torch.float32, device=device))
        quats = torch.tensor(gaussian_splat["rotations"], dtype=torch.float32, device=device)
        colors = torch.tensor(gaussian_splat["sh_coeffs"], dtype=torch.float32, device=device)
        opacities = torch.sigmoid(torch.tensor(gaussian_splat["opacities"], dtype=torch.float32, device=device))
        
        # Camera intrinsics
        fx = fy = width * 0.8
        cx, cy = width / 2, height / 2
        K = torch.tensor([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], device=device)
        
        # Scene center
        scene_z = float(means[:, 2].mean())
        
        frames = []
        total_frames = camera_path["total_frames"]
        positions = camera_path["positions"]
        
        print(f"[Parallax Studio] Rendering {total_frames} frames at {width}×{height}...")
        
        for i in range(total_frames):
            cam_offset = positions[i]
            cam_pos = np.array([cam_offset[0], cam_offset[1], scene_z - 2.5 + cam_offset[2]])
            
            # Build view matrix
            R = np.eye(3)
            T = -R @ cam_pos
            viewmat = np.eye(4)
            viewmat[:3, :3] = R
            viewmat[:3, 3] = T
            viewmat = torch.tensor(viewmat, dtype=torch.float32, device=device)
            
            # Render
            rendered, _, _ = rasterization(
                means=means,
                quats=quats,
                scales=scales,
                opacities=opacities,
                colors=colors,
                viewmats=viewmat[None],
                Ks=K[None],
                width=width,
                height=height,
            )
            
            frame = rendered[0].clamp(0, 1)
            frames.append(frame)
            
            if (i + 1) % 30 == 0:
                print(f"[Parallax Studio] Render progress: {i + 1}/{total_frames}")
        
        frames_tensor = torch.stack(frames, dim=0).cpu()
        
        print(f"[Parallax Studio] ✓ Rendering complete!")
        
        return (frames_tensor,)


class SaveGaussianSplat:
    """Save Gaussian Splat to PLY file."""
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "gaussian_splat": ("GAUSSIAN_SPLAT",),
                "filename_prefix": ("STRING", {"default": "parallax_3d"}),
            }
        }
    
    RETURN_TYPES = ()
    OUTPUT_NODE = True
    FUNCTION = "save"
    CATEGORY = "Parallax Studio/Output"

    def save(self, gaussian_splat, filename_prefix):
        import shutil
        
        output_dir = folder_paths.get_output_directory()
        
        # Find next available filename
        counter = 1
        while True:
            filename = f"{filename_prefix}_{counter:04d}.ply"
            filepath = os.path.join(output_dir, filename)
            if not os.path.exists(filepath):
                break
            counter += 1
        
        # Copy PLY file
        if "ply_path" in gaussian_splat and os.path.exists(gaussian_splat["ply_path"]):
            shutil.copy(gaussian_splat["ply_path"], filepath)
            print(f"[Parallax Studio] ✓ Saved 3D model: {filepath}")
        
        return {}


# Node registration
NODE_CLASS_MAPPINGS = {
    "SHARPModelLoader": SHARPModelLoader,
    "SHARPPredict": SHARPPredict,
    "ParallaxCameraPath": ParallaxCameraPath,
    "GaussianSplatRenderer": GaussianSplatRenderer,
    "SaveGaussianSplat": SaveGaussianSplat,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SHARPModelLoader": "◈ SHARP Model Loader",
    "SHARPPredict": "◈ SHARP Predict (3D Extract)",
    "ParallaxCameraPath": "◈ Parallax Camera Path",
    "GaussianSplatRenderer": "◈ Gaussian Splat Renderer",
    "SaveGaussianSplat": "◈ Save Gaussian Splat",
}
